### ISSUE TITLE
KEEPALIVED could not start

### ISSUE THREAD

**Issue by Paul-LKW** [penglongli/haproxy-keepalived#2]
I just tried your docker image and got failed:

Fri Sep 28 02:50:21 2018: Starting Keepalived v1.3.9 (10/21,2017),
Fri Sep 28 02:50:22 2018: Stopping,
Fri Sep 28 02:50:21 2018: Opening file '/etc/keepalived/keepalived.conf'.,
Fri Sep 28 02:50:21 2018: Starting VRRP child process, pid=5065,
Fri Sep 28 02:50:21 2018: Registering Kernel netlink reflector,
Fri Sep 28 02:50:21 2018: Registering Kernel netlink command channel,
Fri Sep 28 02:50:21 2018: Registering gratuitous ARP shared channel,
Fri Sep 28 02:50:21 2018: WARNING - default user 'keepalived_script' for script execution does not exist - please create.,
Fri Sep 28 02:50:21 2018: Cant find interface ens18 for vrrp_instance VI_1 !!!,
Fri Sep 28 02:50:21 2018:      ens18 no match, ignoring...,
Fri Sep 28 02:50:21 2018: VRRP_Instance(VI_1) Unknown interface !,
Fri Sep 28 02:50:22 2018: Stopped,
Fri Sep 28 02:50:22 2018: Keepalived_vrrp exited with permanent error CONFIG. Terminating,
ERROR: Keepalived start failed, attempting restart .

How could I fix such error ?
Thanks in advance

**Comment by Paul-LKW** [comment]
After I changed the KEEPALIVED_INTERFACE to "eth0" I could see the Keepalived started but still get error LOG below;


Tue Oct  2 02:28:36 2018: Using LinkWatch kernel netlink reflector...,
Tue Oct  2 02:28:36 2018: VRRP sockpool: [ifindex(510), proto(112), unicast(0), fd(9,10)],
Tue Oct  2 02:28:37 2018: VRRP_Instance(VI_1) Transition to MASTER STATE,
Tue Oct  2 02:28:38 2018: VRRP_Instance(VI_1) Entering MASTER STATE,
Tue Oct  2 02:28:38 2018: VRRP_Instance(VI_1) setting protocol VIPs.,
**_Tue Oct  2 02:28:38 2018: Netlink: error: Operation not permitted, type=(20), seq=1538447317, pid=0,_**
Tue Oct  2 02:28:38 2018: Sending gratuitous ARP on eth0 for 192.168.1.98,
Tue Oct  2 02:28:38 2018: VRRP_Instance(VI_1) Sending/queueing gratuitous ARPs on eth0 for 192.168.1.98,
Tue Oct  2 02:28:43 2018: Sending gratuitous ARP on eth0 for 192.168.1.98,
Tue Oct  2 02:28:43 2018: VRRP_Instance(VI_1) Sending/queueing gratuitous ARPs on eth0 for 192.168.1.98

this time Netlink Error !!!

Please help how to fix ?

**Comment by Paul-LKW** [comment]
Finally know what the problem does, this docker should not run under Docker Swarm, and I could use this outside the DS now.

**Comment by penglongli** [comment]
> Finally know what the problem does, this docker should not run under Docker Swarm, and I could use this outside the DS now.

I'm sorry that i have a late reply.  This version is a bit crude, i'll refactor a new version with detailed README. If you have some questions, welcome open an ISSUE. :)

**Comment by penglongli** [comment]
@Paul-LKW @dmolik The latest version had update. You can look it with README.md. And i will add rsyslog for it recently. Hope this can help you.
