### ISSUE TITLE
Cannot point to backend servers

### ISSUE THREAD

**Issue by alexarnoldy** [penglongli/haproxy-keepalived#4]
Hello,

This works very well with the configuration provided but when I try to add frontend and backend binding parameters, haproxy fails to start.

Do you have an example of how to bind to the IP being maintained by keepalived and to several backend servers?

Thanks in advance,

--Alex.

**Comment by penglongli** [comment]
Can you post your configuration files and logs? It would be better if more information could be provided.

**Comment by alexarnoldy** [comment]
Thanks for your your quick response.

Here is the haproxy.cfg:
global
    daemon
    maxconn 30000
    log 127.0.0.1 local0 debug

defaults
    log global
    option tcplog
    mode tcp
    maxconn 30000
    timeout connect 30000
    timeout client 1800000
    timeout server 1800000
    timeout check 1000
    log-format %ci\ [id=%ID]\ [%t]\ %f\ %b/%s\ %Tq/%Tw/%Tc/%Tr/%Tt\ %ST\ %B\ %CC\ %CS\ %tsc\ %ac/%fc/%bc/%sc/%rc\ %sq/%bq\ {%hrl}\ {%hsl}\ %{+Q}r

listen stats
    bind *:1080
    mode http
    stats refresh 30s
    stats uri /stats

frontend master-in
    bind 172.16.240.62:6443
    default_backend servers

backend servers
    server master1 172.16.240.53:6443 maxconn 32
    server master2 172.16.240.54:6443 maxconn 32
    server master3 172.16.240.55:6443 maxconn 32

Here is the keepalived.conf:

vrrp_script chk_haproxy {
    script "/usr/local/bin/chk_haproxy.sh"
    interval 2
    weight 2
    rise 2
    fall 2
}

vrrp_instance VI_1 {
    state MASTER                # keepalived state
    interface br240              # replace this with your interface
    virtual_router_id 40        
    priority 110
    track_interface {
        br240                    # replace this with your interface
    }
    virtual_ipaddress {
        172.16.240.62           # replace this with your virtual IP
    }
    track_script {
        chk_haproxy
    }
    nopreempt
}

I'll drop the logs into the next comment.

**Comment by alexarnoldy** [comment]
Here's the log:
admin@infra1:~> docker logs -f haproxy-keepalived
[INFO] HAProxy is starting.
[INFO] HAProxy started.
[INFO] Keepalived is starting.
Sun Apr 28 20:55:17 2019: Starting Keepalived v1.3.9 (10/21,2017)
Sun Apr 28 20:55:17 2019: Opening file '/etc/keepalived/keepalived.conf'.
Sun Apr 28 20:55:17 2019: Starting VRRP child process, pid=18
Sun Apr 28 20:55:17 2019: Registering Kernel netlink reflector
Sun Apr 28 20:55:17 2019: Registering Kernel netlink command channel
Sun Apr 28 20:55:17 2019: Registering gratuitous ARP shared channel
Sun Apr 28 20:55:17 2019: Opening file '/etc/keepalived/keepalived.conf'.
Sun Apr 28 20:55:17 2019: (VI_1): Warning - nopreempt will not work with initial state MASTER
Sun Apr 28 20:55:17 2019: VRRP_Instance(VI_1) removing protocol VIPs.
Sun Apr 28 20:55:17 2019: ------< Global definitions >------
Sun Apr 28 20:55:17 2019:  Router ID = infra1.aba.com
Sun Apr 28 20:55:17 2019:  Default interface = eth0
Sun Apr 28 20:55:17 2019:  LVS flush = false
Sun Apr 28 20:55:17 2019:  VRRP IPv4 mcast group = 224.0.0.18
Sun Apr 28 20:55:17 2019:  VRRP IPv6 mcast group = ff02::12
Sun Apr 28 20:55:17 2019:  Gratuitous ARP delay = 5
Sun Apr 28 20:55:17 2019:  Gratuitous ARP repeat = 5
Sun Apr 28 20:55:17 2019:  Gratuitous ARP refresh timer = 0
Sun Apr 28 20:55:17 2019:  Gratuitous ARP refresh repeat = 1
Sun Apr 28 20:55:17 2019:  Gratuitous ARP lower priority delay = 5
Sun Apr 28 20:55:17 2019:  Gratuitous ARP lower priority repeat = 5
Sun Apr 28 20:55:17 2019:  Send advert after receive lower priority advert = true
Sun Apr 28 20:55:17 2019:  Send advert after receive higher priority advert = false
Sun Apr 28 20:55:17 2019:  Gratuitous ARP interval = 0
Sun Apr 28 20:55:17 2019:  Gratuitous NA interval = 0
Sun Apr 28 20:55:17 2019:  VRRP default protocol version = 2
Sun Apr 28 20:55:17 2019:  Iptables input chain = INPUT
Sun Apr 28 20:55:17 2019:  VRRP check unicast_src = false
Sun Apr 28 20:55:17 2019:  VRRP skip check advert addresses = false
Sun Apr 28 20:55:17 2019:  VRRP strict mode = false
Sun Apr 28 20:55:17 2019:  VRRP process priority = 0
Sun Apr 28 20:55:17 2019:  VRRP don't swap = false
Sun Apr 28 20:55:17 2019:  Checker process priority = 0
Sun Apr 28 20:55:17 2019:  Checker don't swap = false
Sun Apr 28 20:55:17 2019:  Network namespace = (default)
Sun Apr 28 20:55:17 2019:  Script security disabled
Sun Apr 28 20:55:17 2019:  Default script uid:gid 0:0
Sun Apr 28 20:55:17 2019: ------< VRRP Topology >------
Sun Apr 28 20:55:17 2019:  VRRP Instance = VI_1
Sun Apr 28 20:55:17 2019:    Using VRRPv2
Sun Apr 28 20:55:17 2019:    Want State = MASTER
Sun Apr 28 20:55:17 2019:    Running on device = br240
Sun Apr 28 20:55:17 2019:    Skip checking advert IP addresses = no
Sun Apr 28 20:55:17 2019:    Enforcing strict VRRP compliance = no
Sun Apr 28 20:55:17 2019:    Using src_ip = 172.16.240.47
Sun Apr 28 20:55:17 2019:    Gratuitous ARP delay = 5
Sun Apr 28 20:55:17 2019:    Gratuitous ARP repeat = 5
Sun Apr 28 20:55:17 2019:    Gratuitous ARP refresh timer = 0
Sun Apr 28 20:55:17 2019:    Gratuitous ARP refresh repeat = 1
Sun Apr 28 20:55:17 2019:    Gratuitous ARP lower priority delay = 5
Sun Apr 28 20:55:17 2019:    Gratuitous ARP lower priority repeat = 5
Sun Apr 28 20:55:17 2019:    Send advert after receive lower priority advert = true
Sun Apr 28 20:55:17 2019:    Send advert after receive higher priority advert = false
Sun Apr 28 20:55:17 2019:    Virtual Router ID = 40
Sun Apr 28 20:55:17 2019:    Priority = 110
Sun Apr 28 20:55:17 2019:    Advert interval = 1 sec
Sun Apr 28 20:55:17 2019:    Accept enabled
Sun Apr 28 20:55:17 2019:    Preempt disabled
Sun Apr 28 20:55:17 2019:    Promote_secondaries disabled
Sun Apr 28 20:55:17 2019:    Tracked interfaces = 1
Sun Apr 28 20:55:17 2019:      br240 weight 0
Sun Apr 28 20:55:17 2019:    Virtual IP = 1
Sun Apr 28 20:55:17 2019:      172.16.240.52/32 dev br240 scope global
Sun Apr 28 20:55:17 2019: ------< NIC >------
Sun Apr 28 20:55:17 2019:  Name = lo
Sun Apr 28 20:55:17 2019:  index = 1
Sun Apr 28 20:55:17 2019:  IPv4 address = 127.0.0.1
Sun Apr 28 20:55:17 2019:  IPv6 address = ::
Sun Apr 28 20:55:17 2019:  is UP
Sun Apr 28 20:55:17 2019:  is RUNNING
Sun Apr 28 20:55:17 2019:  MTU = 65536
Sun Apr 28 20:55:17 2019:  HW Type = LOOPBACK
Sun Apr 28 20:55:17 2019: ------< NIC >------
Sun Apr 28 20:55:17 2019:  Name = eth0
Sun Apr 28 20:55:17 2019:  index = 2
Sun Apr 28 20:55:17 2019:  IPv4 address = 0.0.0.0
Sun Apr 28 20:55:17 2019:  IPv6 address = ::
Sun Apr 28 20:55:17 2019:  MAC = 3c:4a:92:dd:87:a8
Sun Apr 28 20:55:17 2019:  is UP
Sun Apr 28 20:55:17 2019:  is RUNNING
Sun Apr 28 20:55:17 2019:  MTU = 1500
Sun Apr 28 20:55:17 2019:  HW Type = ETHERNET
Sun Apr 28 20:55:17 2019: ------< NIC >------
Sun Apr 28 20:55:17 2019:  Name = eth1
Sun Apr 28 20:55:17 2019:  index = 3
Sun Apr 28 20:55:17 2019:  IPv4 address = 0.0.0.0
Sun Apr 28 20:55:17 2019:  IPv6 address = ::
Sun Apr 28 20:55:17 2019:  MAC = 3c:4a:92:dd:87:a8
Sun Apr 28 20:55:17 2019:  is UP
Sun Apr 28 20:55:17 2019:  is RUNNING
Sun Apr 28 20:55:17 2019:  MTU = 1500
Sun Apr 28 20:55:17 2019:  HW Type = ETHERNET
Sun Apr 28 20:55:17 2019: ------< NIC >------
Sun Apr 28 20:55:17 2019:  Name = docker0
Sun Apr 28 20:55:17 2019:  index = 4
Sun Apr 28 20:55:17 2019:  IPv4 address = 172.17.0.1
Sun Apr 28 20:55:17 2019:  IPv6 address = fe80::42:baff:fe04:3e4
Sun Apr 28 20:55:17 2019:  MAC = 02:42:ba:04:03:e4
Sun Apr 28 20:55:17 2019:  is UP
Sun Apr 28 20:55:17 2019:  MTU = 1500
Sun Apr 28 20:55:17 2019:  HW Type = ETHERNET
Sun Apr 28 20:55:17 2019: ------< NIC >------
Sun Apr 28 20:55:17 2019:  Name = bond0
Sun Apr 28 20:55:17 2019:  index = 5
Sun Apr 28 20:55:17 2019:  IPv4 address = 0.0.0.0
Sun Apr 28 20:55:17 2019:  IPv6 address = fe80::3e4a:92ff:fedd:87a8
Sun Apr 28 20:55:17 2019:  MAC = 3c:4a:92:dd:87:a8
Sun Apr 28 20:55:17 2019:  is UP
Sun Apr 28 20:55:17 2019:  is RUNNING
Sun Apr 28 20:55:17 2019:  MTU = 1500
Sun Apr 28 20:55:17 2019:  HW Type = ETHERNET
Sun Apr 28 20:55:17 2019: ------< NIC >------
Sun Apr 28 20:55:17 2019:  Name = br240
Sun Apr 28 20:55:17 2019:  index = 6
Sun Apr 28 20:55:17 2019:  IPv4 address = 172.16.240.47
Sun Apr 28 20:55:17 2019:  IPv6 address = fe80::3e4a:92ff:fedd:87a8
Sun Apr 28 20:55:17 2019:  MAC = 3c:4a:92:dd:87:a8
Sun Apr 28 20:55:17 2019:  is UP
Sun Apr 28 20:55:17 2019:  is RUNNING
Sun Apr 28 20:55:17 2019:  MTU = 1500
Sun Apr 28 20:55:17 2019:  HW Type = ETHERNET
Sun Apr 28 20:55:17 2019: ------< NIC >------
Sun Apr 28 20:55:17 2019:  Name = br200
Sun Apr 28 20:55:17 2019:  index = 7
Sun Apr 28 20:55:17 2019:  IPv4 address = 172.16.200.119
Sun Apr 28 20:55:17 2019:  IPv6 address = fe80::3e4a:92ff:fedd:87a8
Sun Apr 28 20:55:17 2019:  MAC = 3c:4a:92:dd:87:a8
Sun Apr 28 20:55:17 2019:  is UP
Sun Apr 28 20:55:17 2019:  is RUNNING
Sun Apr 28 20:55:17 2019:  MTU = 1500
Sun Apr 28 20:55:17 2019:  HW Type = ETHERNET
Sun Apr 28 20:55:17 2019: ------< NIC >------
Sun Apr 28 20:55:17 2019:  Name = vlan200
Sun Apr 28 20:55:17 2019:  index = 8
Sun Apr 28 20:55:17 2019:  IPv4 address = 0.0.0.0
Sun Apr 28 20:55:17 2019:  IPv6 address = ::
Sun Apr 28 20:55:17 2019:  MAC = 3c:4a:92:dd:87:a8
Sun Apr 28 20:55:17 2019:  is UP
Sun Apr 28 20:55:17 2019:  is RUNNING
Sun Apr 28 20:55:17 2019:  MTU = 1500
Sun Apr 28 20:55:17 2019:  HW Type = ETHERNET
Sun Apr 28 20:55:17 2019: ------< NIC >------
Sun Apr 28 20:55:17 2019:  Name = vnet0
Sun Apr 28 20:55:17 2019:  index = 10
Sun Apr 28 20:55:17 2019:  IPv4 address = 0.0.0.0
Sun Apr 28 20:55:17 2019:  IPv6 address = fe80::fc54:ff:feac:e7cd
Sun Apr 28 20:55:17 2019:  MAC = fe:54:00:ac:e7:cd
Sun Apr 28 20:55:17 2019:  is UP
Sun Apr 28 20:55:17 2019:  is RUNNING
Sun Apr 28 20:55:17 2019:  MTU = 1500
Sun Apr 28 20:55:17 2019:  HW Type = ETHERNET
Sun Apr 28 20:55:17 2019: ------< NIC >------
Sun Apr 28 20:55:17 2019:  Name = vnet2
Sun Apr 28 20:55:17 2019:  index = 12
Sun Apr 28 20:55:17 2019:  IPv4 address = 0.0.0.0
Sun Apr 28 20:55:17 2019:  IPv6 address = fe80::fc54:ff:feec:b46a
Sun Apr 28 20:55:17 2019:  MAC = fe:54:00:ec:b4:6a
Sun Apr 28 20:55:17 2019:  is UP
Sun Apr 28 20:55:17 2019:  is RUNNING
Sun Apr 28 20:55:17 2019:  MTU = 1500
Sun Apr 28 20:55:17 2019:  HW Type = ETHERNET
Sun Apr 28 20:55:17 2019: ------< NIC >------
Sun Apr 28 20:55:17 2019:  Name = vnet1
Sun Apr 28 20:55:17 2019:  index = 17
Sun Apr 28 20:55:17 2019:  IPv4 address = 0.0.0.0
Sun Apr 28 20:55:17 2019:  IPv6 address = fe80::fc54:ff:fe6c:62fd
Sun Apr 28 20:55:17 2019:  MAC = fe:54:00:6c:62:fd
Sun Apr 28 20:55:17 2019:  is UP
Sun Apr 28 20:55:17 2019:  is RUNNING
Sun Apr 28 20:55:17 2019:  MTU = 1500
Sun Apr 28 20:55:17 2019:  HW Type = ETHERNET
Sun Apr 28 20:55:17 2019: Using LinkWatch kernel netlink reflector...
Sun Apr 28 20:55:17 2019: VRRP sockpool: [ifindex(6), proto(112), unicast(0), fd(10,11)]
[WARNING] 117/205517 (14) : parsing [/usr/local/etc/haproxy/haproxy.cfg:15]: 'log-format' overrides previous 'option tcplog' in 'defaults' section.
[ALERT] 117/205517 (14) : Parsing [/usr/local/etc/haproxy/haproxy.cfg:15]: failed to parse log-format : format variable 'ID' is reserved for HTTP mode.
[ALERT] 117/205517 (14) : Fatal errors found in configuration.
Sun Apr 28 20:55:17 2019: VRRP_Instance(VI_1) Transition to MASTER STATE
Sun Apr 28 20:55:18 2019: VRRP_Instance(VI_1) Entering MASTER STATE
Sun Apr 28 20:55:18 2019: VRRP_Instance(VI_1) setting protocol VIPs.
Sun Apr 28 20:55:18 2019: Sending gratuitous ARP on br240 for 172.16.240.52
Sun Apr 28 20:55:18 2019: VRRP_Instance(VI_1) Sending/queueing gratuitous ARPs on br240 for 172.16.240.52
Sun Apr 28 20:55:18 2019: Sending gratuitous ARP on br240 for 172.16.240.52
Sun Apr 28 20:55:18 2019: Sending gratuitous ARP on br240 for 172.16.240.52
Sun Apr 28 20:55:18 2019: Sending gratuitous ARP on br240 for 172.16.240.52
Sun Apr 28 20:55:18 2019: Sending gratuitous ARP on br240 for 172.16.240.52
Sun Apr 28 20:55:23 2019: Sending gratuitous ARP on br240 for 172.16.240.52
Sun Apr 28 20:55:23 2019: VRRP_Instance(VI_1) Sending/queueing gratuitous ARPs on br240 for 172.16.240.52
Sun Apr 28 20:55:23 2019: Sending gratuitous ARP on br240 for 172.16.240.52
Sun Apr 28 20:55:23 2019: Sending gratuitous ARP on br240 for 172.16.240.52
Sun Apr 28 20:55:23 2019: Sending gratuitous ARP on br240 for 172.16.240.52
Sun Apr 28 20:55:23 2019: Sending gratuitous ARP on br240 for 172.16.240.52

**Comment by alexarnoldy** [comment]
The problem is that HAProxy isn't running:

ps -ef | egrep "(haproxy|keepalived)" | grep -v grep
root      1711  1708  0 13:55 pts/0    00:00:00 keepalived --dont-fork --dump-conf --log-console --log-detail --log-facility 7 --vrrp -f /etc/keepalived/keepalived.conf
root      1714  1711  0 13:55 pts/0    00:00:00 keepalived --dont-fork --dump-conf --log-console --log-detail --log-facility 7 --vrrp -f /etc/keepalived/keepalived.conf

Thanks in advance for your help!

**Comment by penglongli** [comment]
According to the error log:
```
[WARNING] 117/205517 (14) : parsing [/usr/local/etc/haproxy/haproxy.cfg:15]: 'log-format' overrides previous 'option tcplog' in 'defaults' section.
[ALERT] 117/205517 (14) : Parsing [/usr/local/etc/haproxy/haproxy.cfg:15]: failed to parse log-format : format variable 'ID' is reserved for HTTP mode.
[ALERT] 117/205517 (14) : Fatal errors found in configuration.
```
You can remove `log-format` in `haproxy.cfg`. 

Because HTTP mode not support `id=%ID`, it only support for TCP mode. You can refer to the documentation to write your own log-format: http://cbonte.github.io/haproxy-dconv/1.7/configuration.html#8.2.1
