### ISSUE TITLE
keepalived stopped(windows docker)

### ISSUE THREAD

**Issue by zddgit** [penglongli/haproxy-keepalived#5]
Configuration file '/etc/keepalived/keepalived.conf' is not a regular non-executable file

 docker inspect

"HostConfig": {
            "Binds": [
                "/host_mnt/c/Users/XX/Desktop/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg",
                "/host_mnt/c/Users/XX/Desktop/keepalived/keepalived.conf:/etc/keepalived/keepalived.conf"]

**Comment by penglongli** [comment]
Please make sure that the file `/host_mnt/c/Users/XX/Desktop/keepalived/keepalived.conf` is existed

**Comment by zddgit** [comment]
必须存在啊！和ha一样得，ha可以启动，keeoalived不能启动，然后进程就崩溃，最后容器退出了

**Comment by penglongli** [comment]
先分析下是不是挂载失败了，在容器启动的时候确定下容器中是不是存在这个文件：
```
/etc/keepalived/keepalived.conf
```
如果确定存在这个文件的话，那可能就是权限有问题。
我对 Windows 下边 Docker 怎么跑的不是很了解，大概率是 `keepalived.conf` 并没有挂到容器里边，或者挂的有问题

**Comment by drce** [comment]
windows docker 不能运行吗：Configuration file '/etc/keepalived/keepalived.conf' is not a regular non-executable file

**Comment by penglongli** [comment]
> windows docker 不能运行吗：Configuration file '/etc/keepalived/keepalived.conf' is not a regular non-executable file

不好意思啊，我确实没在 PC 上验证过，手边没有 PC 的机器..

**Comment by drce** [comment]
你好，我又来了，windows下运行是不是没有对配置文件赋予可执行权限？

**Comment by penglongli** [comment]
> 你好，我又来了，windows下运行是不是没有对配置文件赋予可执行权限？

我估计可能跟 Win 下边的 Docker 安装有问题。看是否能够通过这样的命令覆盖 Entrypoint 来先把容器拉起来
``` bash
docker run -it -d --name haproxy-keepalived --net=host --privileged \
    --entrypoint /bin/sleep \
    -v /root/haproxy-keepalived/haproxy/:/usr/local/etc/haproxy/ \
    -v /root/haproxy-keepalived/keepalived/:/etc/keepalived/ \
    pelin/haproxy-keepalived:v1.0.0 \
    "1000000"
```
(注意 `-v` 改成你自己的，或者这两行删掉也行，会用默认的)

然后进入到容器里边，手动跑一下这个命令，看下什么报错
```
/haproxy-keepalived
```

## 进一步排查

因为是一个容器里边跑了两个进程：HAProxy 和 Keepalived，所以可以在进入容器后，对两个进程分别单独去启动，看看是哪个进程会启动失败：
```bash
keepalived  --dont-fork --dump-conf --log-console --log-detail --log-facility 7 --vrrp -f /etc/keepalived/keepalived.conf

/usr/local/sbin/haproxy -p /run/haproxy.pid -db -f /usr/local/etc/haproxy/haproxy.cfg -W 
```

**Comment by drce** [comment]
你好，按照你的方法，我把容器拉起来了，然后使用命令chmod -R 644 /etc/keepalived可以运行了
另外找到原因了：
当使用D:\data\haproxy_keepalived\rabbitmq\k2:/etc/keepalived挂载的时候，windows下会有权限问题，
但是使用： -v D:\data\haproxy_keepalived\rabbitmq\k1\keepalived.conf:/etc/keepalived/keepalived.conf -v D:\data\haproxy_keepalived\rabbitmq\k1\check_haproxy.sh:/etc/keepalived/check_haproxy.sh
没有这个问题

**Comment by penglongli** [comment]
> 你好，按照你的方法，我把容器拉起来了，然后使用命令chmod -R 644 /etc/keepalived可以运行了
> 另外找到原因了：
> 当使用D:\data\haproxy_keepalived\rabbitmq\k2:/etc/keepalived挂载的时候，windows下会有权限问题，
> 但是使用： -v D:\data\haproxy_keepalived\rabbitmq\k1\keepalived.conf:/etc/keepalived/keepalived.conf -v D:\data\haproxy_keepalived\rabbitmq\k1\check_haproxy.sh:/etc/keepalived/check_haproxy.sh
> 没有这个问题

好的，挂目录是为了能够让虚机的配置文件，动态映射进容器里边，然后配置文件修改就可以不停机更新 HAProxy。

参见：https://github.com/penglongli/haproxy-keepalived#dynamic-reload-haproxy

只是没想到 Win 下边会有这种问题

**Comment by franktrue** [comment]
> 你好，按照你的方法，我把容器拉起来了，然后使用命令chmod -R 644 /etc/keepalived可以运行了
> 另外找到原因了：
> 当使用D:\data\haproxy_keepalived\rabbitmq\k2:/etc/keepalived挂载的时候，windows下会有权限问题，
> 但是使用： -v D:\data\haproxy_keepalived\rabbitmq\k1\keepalived.conf:/etc/keepalived/keepalived.conf -v D:\data\haproxy_keepalived\rabbitmq\k1\check_haproxy.sh:/etc/keepalived/check_haproxy.sh
> 没有这个问题

我也遇到这个问题，最后终于发现是权限问题，可是在docker里面chmod -R 644 keepalived.conf 无效……

**Comment by drce** [comment]
> > 你好，按照你的方法，我把容器拉起来了，然后使用命令chmod -R 644 /etc/keepalived可以运行了
> > 另外找到原因了：
> > 当使用D:\data\haproxy_keepalived\rabbitmq\k2:/etc/keepalived挂载的时候，windows下会有权限问题，
> > 但是使用： -v D:\data\haproxy_keepalived\rabbitmq\k1\keepalived.conf:/etc/keepalived/keepalived.conf -v D:\data\haproxy_keepalived\rabbitmq\k1\check_haproxy.sh:/etc/keepalived/check_haproxy.sh
> > 没有这个问题
> 
> 我也遇到这个问题，最后终于发现是权限问题，可是在docker里面chmod -R 644 keepalived.conf 无效……

我自己手动nginx keepalived模块了
