### ISSUE TITLE
网卡没有对应的vip

### ISSUE THREAD

**Issue by p2gg** [penglongli/haproxy-keepalived#6]
我在win10下的vmware安装了centos(防火墙已关), 在centos下运行docker, docker内运行了nginx容器(映射80:80), 再运行了该镜像, 然后centos下可以正常curl nigix网页, 也可以curl vip访问对应的网页, 可是对应的网卡ens33没有绑定vip, 外部win10无法访问. 我尝试了在centos下直接安装keepalived问题依旧, 不清楚具体原因.

**Comment by penglongli** [comment]
这个比较久了，我也记不太清楚。

你在虚拟机上执行 ifconfig，贴出来看看。然后贴一下你 win10 在 cmd 执行 ipconfig 的内容。看看是不是因为你 vmware 的网络模式导致不能通
