### ISSUE TITLE
Reloading haproxy config with docker kill -s HUP haproxy-keepalived  not working

### ISSUE THREAD

**Issue by parsonsalan1** [penglongli/haproxy-keepalived#7]
Usually you run docker kill -s HUP haproxy-keepalived  to reload the config with no downtime, but changes are not being updated unless container reboot.

**Comment by penglongli** [comment]
Yes, you're right. I think i need to re-design this repo, and adapt it to Kubernetes.

Thanks for you suggestion, i'll close this issue if i completed it.

**Comment by penglongli** [comment]
Hi I refactored this repo.  

Please use tag `v1.0.0`, this version will support `docker kill -s HUP`
