### ISSUE TITLE
Configuration file '/etc/keepalived/keepalived.conf' is not a regular non-executable file

### ISSUE THREAD

**Issue by lvbaocheng** [penglongli/haproxy-keepalived#8]
宿主环境为centos7

docker-compose.yml
##
version: "3"
services:
  haproxy:
    image: pelin/haproxy-keepalived:v1.0.0
    container_name: ha-kpali-01
    ports:
        - "4001:8888"
        - "4002:3306"
    volumes:
        - /home/docker/haproxy/ha-01/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
        - /home/docker/haproxy/kpali-01/keepalived.conf:/etc/keepalived/keepalived.conf
    privileged: true
    #restart: always
    networks:
        - default
    #sysctls:
    ##    - net.ipv4.ip_unprivileged_port_start=0
    #command: haproxy -c -f /usr/local/etc/haproxy/haproxy.cfg

networks:
  default:
    external:
        name: haproxy-keepalived-network
##

文件keepalived.conf和haproxy.cnf授权 chmod 777
没道理不行的 除了文件的所属用户组/用户为root root 没改变，因为不知道容器里的默认用户是什么

**Comment by penglongli** [comment]
我尝试了一下这个 docker-compose.yaml
``` bash
version: "3"
services:
  haproxy:
    network_mode: host
    image: pelin/haproxy-keepalived:v1.0.0
    container_name: ha-kpali-01
    volumes:
      - /root/workspace/haproxy-keepalived/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - /root/workspace/haproxy-keepalived/keepalived.conf:/etc/keepalived/keepalived.conf
    privileged: true
```
使用 `docker-compose up` 能正常启动

方便发一下 `keepalived.conf` 的配置以及在启动的时候整体的日志信息吗？

**Comment by lvbaocheng** [comment]
问题解决了，感谢作者，还是配置导致的问题

keepalived.conf
##
vrrp_instance VI_1 {
        state MASTER  #keepalived MASTER BACKUP 主备身份
        interface em1  #宿主主机网卡  **### 这个问题在这，interface 的网卡是容器的网卡名字，不是宿主主机的网卡**
        virtual_router_id 51  #虚拟路由标识，主备必须一致 0-255
        priority 100  #权重
        advert_int 1  #心跳检测 1s 主备须一致
        authentication {  #主备验证方式 主备密码须一致
            auth_type PASS
            auth_pass 1111
        }
        virtual_ipaddress {  #虚拟IP
            172.11.0.2
        }
    }

    virtual_server 172.11.0.2 8888 {
        delay_loop 3
        lb_algo rr
        lb_kind NAT
        persistence_timeout 50
        protocol TCP

        real_server 172.18.0.201 8888 {
            weight 1
        }
    }

    virtual_server 172.11.0.2 3306 {
        delay_loop 3
        lb_algo rr
        lb_kind NAT
        persistence_timeout 50
        protocol TCP

        real_server 172.18.0.201 3306 {
            weight 1
        }
    }

##
haproxy.cfg
##
global
    #工作目录
    #chroot /usr/local/etc/haproxy   **### 这个配置也会存在问题，导致haproxy启动失败**
    #日志文件，使用rsyslog服务中local5日志设备（/var/log/local5），等级info
    log 127.0.0.1 local5 info
    #守护进程运行
    daemon

defaults
    log global
    mode    http
    #日志格式
    option  httplog
    #日志中不记录负载均衡的心跳检测记录
    option  dontlognull
    #连接超时（毫秒）
    timeout connect 5000
    #客户端超时（毫秒）
    timeout client  50000
    #服务器超时（毫秒）
    timeout server  50000

#监控界面  
listen  admin_stats
    #监控界面的访问的IP和端口
    bind  0.0.0.0:8888
    #访问协议
    mode        http
    #URI相对地址
    stats uri   /dbs
    #统计报告格式
    stats realm     Global statistics
    #登陆帐户信息
    stats auth  admin:5b89e419a23ab93e0da1d097d495746e
#数据库负载均衡
listen  proxy-mysql
    #访问的IP和端口
    bind  0.0.0.0:3306
    #网络协议
    mode  tcp
    #负载均衡算法（轮询算法）
    #轮询算法：roundrobin
    #权重算法：static-rr
    #最少连接算法：leastconn
    #请求源IP算法：source 
    balance  roundrobin
    #日志格式
    option  tcplog
    #在MySQL中创建一个没有权限的haproxy用户，密码为空。Haproxy使用这个账户对MySQL数据库心跳检测
    option  mysql-check user haproxy
    server  MySQL_1_185 172.16.5.185:3301 check weight 1 maxconn 2000
    server  MySQL_2_184 172.16.2.184:3301 check weight 1 maxconn 2000
    #使用keepalive检测死链
    option  tcpka
##

**Comment by penglongli** [comment]
> 这个问题在这，interface 的网卡是容器的网卡名字，不是宿主主机的网卡

我见你配置了一个 network 网络，这样子不好，需要换成 hostNetwork。

因为 Keepalived 就是监听你本机的网卡的，如果机器挂了，virtual ip 就漂移到其它机器上

**Comment by lvbaocheng** [comment]
你的意思是配置都得这个网络haproxy-keepalived-network  改为容器采用host的方式？
我尝试找找更详细的资料看看，谢谢你
